name: Generate stats card

on:
  schedule:
    # Every Monday at 00:00 UTC
    - cron: "0 0 * * 1"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate stats.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&hide_title=true&hide_rank=true&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=ayu-mirage&locale=en&hide_border=false&custom_title=SMNFL%20Stats
          path: dist/stats.svg
          token: ${{ secrets.TOKEN_PAT }}
          fail_on_error: true

      - name: Push stats.svg to stats-output
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist

          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b stats-output
          git add stats.svg
          git commit -m "Update stats card"

          git remote add origin \
            "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git push --force origin stats-output
